### PR TITLE
image bug fix

### PR DESCRIPTION
**Pull request by tamerlantian**
fix
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks tamerlantian, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "package-lock.json" from your PR and use yarn instead.

**Review by tamerlantian — COMMENTED** [review]
review this bug fix again, please.

**Pull request closed without merging**
